"""Structural host adapter contract, with no private runtime imports."""
from typing import Callable, Protocol, Iterable
from .ai import AIProtocol, PluginAIProtocol
from .clinical_ai import TrichologySummaryRegistration

class RegistryProtocol(Protocol):
    def register_trichology_summary(self, plugin_id: str, registration: TrichologySummaryRegistration) -> None: ...
    def trichology_summaries(self) -> Iterable[tuple[str, TrichologySummaryRegistration]]: ...
    def register_ui_hook(self, plugin_id: str, hook: str, renderer: Callable) -> None: ...
    def ui_hooks(self, hook: str) -> Iterable[tuple[str, Callable]]: ...
